#ifndef MICROTCP_LOGGING_COLORS_H
#define MICROTCP_LOGGING_COLORS_H

#include "cli_color.h"

#define LOG_INFO_COLOR COLOR_FG_BLUE
#define LOG_WARNING_COLOR COLOR_FG_ORANGE
#define LOG_ERROR_COLOR COLOR_FG_RED
#define LOG_MESSAGE_COLOR COLOR_FG_WHITE
#define LOG_DEFAULT_COLOR SGR_RESET COLOR_FG_GRAY

#define LOG_FSM_CONNECT_COLOR COLOR_FG_MINT
#define LOG_FSM_ACCEPT_COLOR COLOR_FG_MINT
#define LOG_FSM_SHUTDOWN_COLOR COLOR_FG_TEAL
#define LOG_FSM_RECV_COLOR COLOR_FG_SKY
#define LOG_FSM_SEND_COLOR COLOR_FG_PINK

#endif /* MICROTCP_LOGGING_COLORS_H */
